### ISSUE TITLE
latin and unicode characters issue when dumping json

### ISSUE THREAD

**Issue by beanrepo** [Colin-b/logging_json#13]
Hi,
i discovered an issue that prints strings with unicode characters as in this example "\u0451".

To fix it I suggest to add parameter ```ensure_ascii=False``` in json.dumps() call at line 99 in logging_json._formatter.py

I hope it will help!

**Comment by Colin-b** [comment]
Hello @BeanRepo ,

Thanks for raising the issue and apologies on the late reply. Could you provide more details? What is the string that you provided and what is the output that you received vs expected?

Thanks again

**Comment by Biswajit2902** [comment]
Hi have solved this problem. I will test then, i will raise a pull request.

@BeanRepo you can check below source code.
 
https://github.com/Biswajit2902/logging_json.git

**Comment by Colin-b** [comment]
Hi @BeanRepo and @Biswajit2902 

This issue is fixed in version `0.5.0` available on pypi as of now.

Thanks for reporting.
