### ISSUE TITLE
How to log additional custom fields ?

### ISSUE THREAD

**Issue by nyue** [Colin-b/logging_json#9]
Hi,

  I have been testing out logging_json over the last couple of days.

  I am able to generate JSON logs.

  I would like to add some custom fields so that they are automatically included in the JSON log without the user having to provide additional information. The value of those fields are either queried via environment variable or in-house modules that have functions to retrieve those information.

  Some of those fields are

  "airport" - value is a string
  "building" - value is an integer
  "linear_dimension" - value is an unsigned integer
  "weight" - value is a floating point number

Cheers

**Comment by Colin-b** [comment]
Hello @nyue ,

The `fields` parameter of the formatter allows to provide those fixed fields values. It's up to you to find out how you can retrieve those values at the time of the formatter creation. May I ask how you configure the formatter?

**Comment by Colin-b** [comment]
Closed for inactivity, feel free to reopen if you still have an issue with the solution offered.
